/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        if (args.length != 1) {
            System.out.println("Usage: java App <string>");
            return;
        }

        String original = args[0];

        String compressed = RLE.compress(original);
        System.out.println("Compressed: " + compressed);

        String decompressed = RLE.decompress(compressed);
        System.out.println("Decompressed: " + decompressed);

        System.out.println("Original and decompressed strings are equal: " + original.equals(decompressed));
    }
}
